package com.lxzl.db.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of å…¬å?¸è?Œå·¥ä¿¡æ?¯è¡¨.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Companyemployeeinfo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private Long ceiid;

	/** è?Œå·¥ä¿¡æ?¯è¡¨. */
	private Employee employee;

	/** å…¬å?¸. */
	private Company company;

	/** åˆ›å»ºæ—¥æœŸ. */
	private Date createTime;

	/** æ›´æ–°æ—¥æœŸ. */
	private Date updateTime;

	/**
	 * Constructor.
	 */
	public Companyemployeeinfo() {
	}

	/**
	 * Set the ID.
	 * 
	 * @param ceiid
	 *            ID
	 */
	public void setCeiid(Long ceiid) {
		this.ceiid = ceiid;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public Long getCeiid() {
		return this.ceiid;
	}

	/**
	 * Set the è?Œå·¥ä¿¡æ?¯è¡¨.
	 * 
	 * @param employee
	 *            è?Œå·¥ä¿¡æ?¯è¡¨
	 */
	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	/**
	 * Get the è?Œå·¥ä¿¡æ?¯è¡¨.
	 * 
	 * @return è?Œå·¥ä¿¡æ?¯è¡¨
	 */
	public Employee getEmployee() {
		return this.employee;
	}

	/**
	 * Set the å…¬å?¸.
	 * 
	 * @param company
	 *            å…¬å?¸
	 */
	public void setCompany(Company company) {
		this.company = company;
	}

	/**
	 * Get the å…¬å?¸.
	 * 
	 * @return å…¬å?¸
	 */
	public Company getCompany() {
		return this.company;
	}

	/**
	 * Set the åˆ›å»ºæ—¥æœŸ.
	 * 
	 * @param createTime
	 *            åˆ›å»ºæ—¥æœŸ
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the åˆ›å»ºæ—¥æœŸ.
	 * 
	 * @return åˆ›å»ºæ—¥æœŸ
	 */
	public Date getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the æ›´æ–°æ—¥æœŸ.
	 * 
	 * @param updateTime
	 *            æ›´æ–°æ—¥æœŸ
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * Get the æ›´æ–°æ—¥æœŸ.
	 * 
	 * @return æ›´æ–°æ—¥æœŸ
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((ceiid == null) ? 0 : ceiid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Companyemployeeinfo other = (Companyemployeeinfo) obj;
		if (ceiid == null) {
			if (other.ceiid != null) {
				return false;
			}
		} else if (!ceiid.equals(other.ceiid)) {
			return false;
		}
		return true;
	}

}
