package com.lxzl.db.bean;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of è?Œå·¥ä¿¡æ?¯è¡¨.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Employee implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private Long edi;

	/** å§“å??. */
	private String name;

	/** å¹´é¾„. */
	private Integer age;

	/** æ€§åˆ«. */
	private String sex;

	/** åˆ›å»ºæ—¥æœŸ. */
	private Date createTime;

	/** æ›´æ–°æ—¥æœŸ. */
	private Date updateTime;

	/** The set of å…¬å?¸è?Œå·¥ä¿¡æ?¯è¡¨. */
	private Set<Companyemployeeinfo> companyemployeeinfoSet;

	/** The set of EmployeeInfo. */
	private Set<Employeeinfo> employeeinfoSet;

	/** The set of å‘˜å·¥çº§åˆ«ä¿¡æ?¯è¡¨. */
	private Set<Employeelevelinfo> employeelevelinfoSet;

	/** The set of è?Œå·¥çŠ¶æ€?ä¿¡æ?¯è¡¨. */
	private Set<Employeestatusinfo> employeestatusinfoSet;

	/** The set of é¡¹ç›®è?Œå·¥ä¿¡æ?¯è¡¨. */
	private Set<Projectemployeeinfo> projectemployeeinfoSet;

	/**
	 * Constructor.
	 */
	public Employee() {
		this.companyemployeeinfoSet = new HashSet<Companyemployeeinfo>();
		this.employeeinfoSet = new HashSet<Employeeinfo>();
		this.employeelevelinfoSet = new HashSet<Employeelevelinfo>();
		this.employeestatusinfoSet = new HashSet<Employeestatusinfo>();
		this.projectemployeeinfoSet = new HashSet<Projectemployeeinfo>();
	}

	/**
	 * Set the ID.
	 * 
	 * @param edi
	 *            ID
	 */
	public void setEdi(Long edi) {
		this.edi = edi;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public Long getEdi() {
		return this.edi;
	}

	/**
	 * Set the å§“å??.
	 * 
	 * @param name
	 *            å§“å??
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the å§“å??.
	 * 
	 * @return å§“å??
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the å¹´é¾„.
	 * 
	 * @param age
	 *            å¹´é¾„
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * Get the å¹´é¾„.
	 * 
	 * @return å¹´é¾„
	 */
	public Integer getAge() {
		return this.age;
	}

	/**
	 * Set the æ€§åˆ«.
	 * 
	 * @param sex
	 *            æ€§åˆ«
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * Get the æ€§åˆ«.
	 * 
	 * @return æ€§åˆ«
	 */
	public String getSex() {
		return this.sex;
	}

	/**
	 * Set the åˆ›å»ºæ—¥æœŸ.
	 * 
	 * @param createTime
	 *            åˆ›å»ºæ—¥æœŸ
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the åˆ›å»ºæ—¥æœŸ.
	 * 
	 * @return åˆ›å»ºæ—¥æœŸ
	 */
	public Date getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the æ›´æ–°æ—¥æœŸ.
	 * 
	 * @param updateTime
	 *            æ›´æ–°æ—¥æœŸ
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * Get the æ›´æ–°æ—¥æœŸ.
	 * 
	 * @return æ›´æ–°æ—¥æœŸ
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * Set the set of the å…¬å?¸è?Œå·¥ä¿¡æ?¯è¡¨.
	 * 
	 * @param companyemployeeinfoSet
	 *            The set of å…¬å?¸è?Œå·¥ä¿¡æ?¯è¡¨
	 */
	public void setCompanyemployeeinfoSet(Set<Companyemployeeinfo> companyemployeeinfoSet) {
		this.companyemployeeinfoSet = companyemployeeinfoSet;
	}

	/**
	 * Add the å…¬å?¸è?Œå·¥ä¿¡æ?¯è¡¨.
	 * 
	 * @param companyemployeeinfo
	 *            å…¬å?¸è?Œå·¥ä¿¡æ?¯è¡¨
	 */
	public void addCompanyemployeeinfo(Companyemployeeinfo companyemployeeinfo) {
		this.companyemployeeinfoSet.add(companyemployeeinfo);
	}

	/**
	 * Get the set of the å…¬å?¸è?Œå·¥ä¿¡æ?¯è¡¨.
	 * 
	 * @return The set of å…¬å?¸è?Œå·¥ä¿¡æ?¯è¡¨
	 */
	public Set<Companyemployeeinfo> getCompanyemployeeinfoSet() {
		return this.companyemployeeinfoSet;
	}

	/**
	 * Set the set of the EmployeeInfo.
	 * 
	 * @param employeeinfoSet
	 *            The set of EmployeeInfo
	 */
	public void setEmployeeinfoSet(Set<Employeeinfo> employeeinfoSet) {
		this.employeeinfoSet = employeeinfoSet;
	}

	/**
	 * Add the EmployeeInfo.
	 * 
	 * @param employeeinfo
	 *            EmployeeInfo
	 */
	public void addEmployeeinfo(Employeeinfo employeeinfo) {
		this.employeeinfoSet.add(employeeinfo);
	}

	/**
	 * Get the set of the EmployeeInfo.
	 * 
	 * @return The set of EmployeeInfo
	 */
	public Set<Employeeinfo> getEmployeeinfoSet() {
		return this.employeeinfoSet;
	}

	/**
	 * Set the set of the å‘˜å·¥çº§åˆ«ä¿¡æ?¯è¡¨.
	 * 
	 * @param employeelevelinfoSet
	 *            The set of å‘˜å·¥çº§åˆ«ä¿¡æ?¯è¡¨
	 */
	public void setEmployeelevelinfoSet(Set<Employeelevelinfo> employeelevelinfoSet) {
		this.employeelevelinfoSet = employeelevelinfoSet;
	}

	/**
	 * Add the å‘˜å·¥çº§åˆ«ä¿¡æ?¯è¡¨.
	 * 
	 * @param employeelevelinfo
	 *            å‘˜å·¥çº§åˆ«ä¿¡æ?¯è¡¨
	 */
	public void addEmployeelevelinfo(Employeelevelinfo employeelevelinfo) {
		this.employeelevelinfoSet.add(employeelevelinfo);
	}

	/**
	 * Get the set of the å‘˜å·¥çº§åˆ«ä¿¡æ?¯è¡¨.
	 * 
	 * @return The set of å‘˜å·¥çº§åˆ«ä¿¡æ?¯è¡¨
	 */
	public Set<Employeelevelinfo> getEmployeelevelinfoSet() {
		return this.employeelevelinfoSet;
	}

	/**
	 * Set the set of the è?Œå·¥çŠ¶æ€?ä¿¡æ?¯è¡¨.
	 * 
	 * @param employeestatusinfoSet
	 *            The set of è?Œå·¥çŠ¶æ€?ä¿¡æ?¯è¡¨
	 */
	public void setEmployeestatusinfoSet(Set<Employeestatusinfo> employeestatusinfoSet) {
		this.employeestatusinfoSet = employeestatusinfoSet;
	}

	/**
	 * Add the è?Œå·¥çŠ¶æ€?ä¿¡æ?¯è¡¨.
	 * 
	 * @param employeestatusinfo
	 *            è?Œå·¥çŠ¶æ€?ä¿¡æ?¯è¡¨
	 */
	public void addEmployeestatusinfo(Employeestatusinfo employeestatusinfo) {
		this.employeestatusinfoSet.add(employeestatusinfo);
	}

	/**
	 * Get the set of the è?Œå·¥çŠ¶æ€?ä¿¡æ?¯è¡¨.
	 * 
	 * @return The set of è?Œå·¥çŠ¶æ€?ä¿¡æ?¯è¡¨
	 */
	public Set<Employeestatusinfo> getEmployeestatusinfoSet() {
		return this.employeestatusinfoSet;
	}

	/**
	 * Set the set of the é¡¹ç›®è?Œå·¥ä¿¡æ?¯è¡¨.
	 * 
	 * @param projectemployeeinfoSet
	 *            The set of é¡¹ç›®è?Œå·¥ä¿¡æ?¯è¡¨
	 */
	public void setProjectemployeeinfoSet(Set<Projectemployeeinfo> projectemployeeinfoSet) {
		this.projectemployeeinfoSet = projectemployeeinfoSet;
	}

	/**
	 * Add the é¡¹ç›®è?Œå·¥ä¿¡æ?¯è¡¨.
	 * 
	 * @param projectemployeeinfo
	 *            é¡¹ç›®è?Œå·¥ä¿¡æ?¯è¡¨
	 */
	public void addProjectemployeeinfo(Projectemployeeinfo projectemployeeinfo) {
		this.projectemployeeinfoSet.add(projectemployeeinfo);
	}

	/**
	 * Get the set of the é¡¹ç›®è?Œå·¥ä¿¡æ?¯è¡¨.
	 * 
	 * @return The set of é¡¹ç›®è?Œå·¥ä¿¡æ?¯è¡¨
	 */
	public Set<Projectemployeeinfo> getProjectemployeeinfoSet() {
		return this.projectemployeeinfoSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((edi == null) ? 0 : edi.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Employee other = (Employee) obj;
		if (edi == null) {
			if (other.edi != null) {
				return false;
			}
		} else if (!edi.equals(other.edi)) {
			return false;
		}
		return true;
	}

}
