package com.lxzl.db.bean;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of è?Œå·¥çŠ¶æ€?è¡¨.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Employeestatus implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private Long esid;

	/** è?Œå·¥çŠ¶æ€?. */
	private String status;

	/** åˆ›å»ºæ—¥æœŸ. */
	private Date createTime;

	/** æ›´æ–°æ—¥æœŸ. */
	private Date updateTime;

	/** The set of è?Œå·¥çŠ¶æ€?ä¿¡æ?¯è¡¨. */
	private Set<Employeestatusinfo> employeestatusinfoSet;

	/**
	 * Constructor.
	 */
	public Employeestatus() {
		this.employeestatusinfoSet = new HashSet<Employeestatusinfo>();
	}

	/**
	 * Set the ID.
	 * 
	 * @param esid
	 *            ID
	 */
	public void setEsid(Long esid) {
		this.esid = esid;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public Long getEsid() {
		return this.esid;
	}

	/**
	 * Set the è?Œå·¥çŠ¶æ€?.
	 * 
	 * @param status
	 *            è?Œå·¥çŠ¶æ€?
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * Get the è?Œå·¥çŠ¶æ€?.
	 * 
	 * @return è?Œå·¥çŠ¶æ€?
	 */
	public String getStatus() {
		return this.status;
	}

	/**
	 * Set the åˆ›å»ºæ—¥æœŸ.
	 * 
	 * @param createTime
	 *            åˆ›å»ºæ—¥æœŸ
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the åˆ›å»ºæ—¥æœŸ.
	 * 
	 * @return åˆ›å»ºæ—¥æœŸ
	 */
	public Date getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the æ›´æ–°æ—¥æœŸ.
	 * 
	 * @param updateTime
	 *            æ›´æ–°æ—¥æœŸ
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * Get the æ›´æ–°æ—¥æœŸ.
	 * 
	 * @return æ›´æ–°æ—¥æœŸ
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * Set the set of the è?Œå·¥çŠ¶æ€?ä¿¡æ?¯è¡¨.
	 * 
	 * @param employeestatusinfoSet
	 *            The set of è?Œå·¥çŠ¶æ€?ä¿¡æ?¯è¡¨
	 */
	public void setEmployeestatusinfoSet(Set<Employeestatusinfo> employeestatusinfoSet) {
		this.employeestatusinfoSet = employeestatusinfoSet;
	}

	/**
	 * Add the è?Œå·¥çŠ¶æ€?ä¿¡æ?¯è¡¨.
	 * 
	 * @param employeestatusinfo
	 *            è?Œå·¥çŠ¶æ€?ä¿¡æ?¯è¡¨
	 */
	public void addEmployeestatusinfo(Employeestatusinfo employeestatusinfo) {
		this.employeestatusinfoSet.add(employeestatusinfo);
	}

	/**
	 * Get the set of the è?Œå·¥çŠ¶æ€?ä¿¡æ?¯è¡¨.
	 * 
	 * @return The set of è?Œå·¥çŠ¶æ€?ä¿¡æ?¯è¡¨
	 */
	public Set<Employeestatusinfo> getEmployeestatusinfoSet() {
		return this.employeestatusinfoSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((esid == null) ? 0 : esid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Employeestatus other = (Employeestatus) obj;
		if (esid == null) {
			if (other.esid != null) {
				return false;
			}
		} else if (!esid.equals(other.esid)) {
			return false;
		}
		return true;
	}

}
