package com.lxzl.db.bean;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of å…¬å?¸.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Company implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** å…¬å?¸ID. */
	private Long cid;

	/** å…¬å?¸å??ç§°. */
	private String name;

	/** å…¬å?¸ä»‹ç»?. */
	private String description;

	/** åˆ›å»ºæ—¥æœŸ. */
	private Date createTime;

	/** æ›´æ–°æ—¥æœŸ. */
	private Date updateTime;

	/** The set of å…¬å?¸è?Œå·¥ä¿¡æ?¯è¡¨. */
	private Set<Companyemployeeinfo> companyemployeeinfoSet;

	/** The set of å…¬å?¸è¯¦ç»†ä¿¡æ?¯. */
	private Set<Companyinfo> companyinfoSet;

	/** The set of å…¬å?¸å®¢æˆ·ä¿¡æ?¯è¡¨. */
	private Set<Customercompanyinfo> customercompanyinfoSet;

	/** The set of é¡¹ç›®è¡¨. */
	private Set<Project> projectSet;

	/**
	 * Constructor.
	 */
	public Company() {
		this.companyemployeeinfoSet = new HashSet<Companyemployeeinfo>();
		this.companyinfoSet = new HashSet<Companyinfo>();
		this.customercompanyinfoSet = new HashSet<Customercompanyinfo>();
		this.projectSet = new HashSet<Project>();
	}

	/**
	 * Set the å…¬å?¸ID.
	 * 
	 * @param cid
	 *            å…¬å?¸ID
	 */
	public void setCid(Long cid) {
		this.cid = cid;
	}

	/**
	 * Get the å…¬å?¸ID.
	 * 
	 * @return å…¬å?¸ID
	 */
	public Long getCid() {
		return this.cid;
	}

	/**
	 * Set the å…¬å?¸å??ç§°.
	 * 
	 * @param name
	 *            å…¬å?¸å??ç§°
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the å…¬å?¸å??ç§°.
	 * 
	 * @return å…¬å?¸å??ç§°
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the å…¬å?¸ä»‹ç»?.
	 * 
	 * @param description
	 *            å…¬å?¸ä»‹ç»?
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Get the å…¬å?¸ä»‹ç»?.
	 * 
	 * @return å…¬å?¸ä»‹ç»?
	 */
	public String getDescription() {
		return this.description;
	}

	/**
	 * Set the åˆ›å»ºæ—¥æœŸ.
	 * 
	 * @param createTime
	 *            åˆ›å»ºæ—¥æœŸ
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the åˆ›å»ºæ—¥æœŸ.
	 * 
	 * @return åˆ›å»ºæ—¥æœŸ
	 */
	public Date getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the æ›´æ–°æ—¥æœŸ.
	 * 
	 * @param updateTime
	 *            æ›´æ–°æ—¥æœŸ
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * Get the æ›´æ–°æ—¥æœŸ.
	 * 
	 * @return æ›´æ–°æ—¥æœŸ
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * Set the set of the å…¬å?¸è?Œå·¥ä¿¡æ?¯è¡¨.
	 * 
	 * @param companyemployeeinfoSet
	 *            The set of å…¬å?¸è?Œå·¥ä¿¡æ?¯è¡¨
	 */
	public void setCompanyemployeeinfoSet(Set<Companyemployeeinfo> companyemployeeinfoSet) {
		this.companyemployeeinfoSet = companyemployeeinfoSet;
	}

	/**
	 * Add the å…¬å?¸è?Œå·¥ä¿¡æ?¯è¡¨.
	 * 
	 * @param companyemployeeinfo
	 *            å…¬å?¸è?Œå·¥ä¿¡æ?¯è¡¨
	 */
	public void addCompanyemployeeinfo(Companyemployeeinfo companyemployeeinfo) {
		this.companyemployeeinfoSet.add(companyemployeeinfo);
	}

	/**
	 * Get the set of the å…¬å?¸è?Œå·¥ä¿¡æ?¯è¡¨.
	 * 
	 * @return The set of å…¬å?¸è?Œå·¥ä¿¡æ?¯è¡¨
	 */
	public Set<Companyemployeeinfo> getCompanyemployeeinfoSet() {
		return this.companyemployeeinfoSet;
	}

	/**
	 * Set the set of the å…¬å?¸è¯¦ç»†ä¿¡æ?¯.
	 * 
	 * @param companyinfoSet
	 *            The set of å…¬å?¸è¯¦ç»†ä¿¡æ?¯
	 */
	public void setCompanyinfoSet(Set<Companyinfo> companyinfoSet) {
		this.companyinfoSet = companyinfoSet;
	}

	/**
	 * Add the å…¬å?¸è¯¦ç»†ä¿¡æ?¯.
	 * 
	 * @param companyinfo
	 *            å…¬å?¸è¯¦ç»†ä¿¡æ?¯
	 */
	public void addCompanyinfo(Companyinfo companyinfo) {
		this.companyinfoSet.add(companyinfo);
	}

	/**
	 * Get the set of the å…¬å?¸è¯¦ç»†ä¿¡æ?¯.
	 * 
	 * @return The set of å…¬å?¸è¯¦ç»†ä¿¡æ?¯
	 */
	public Set<Companyinfo> getCompanyinfoSet() {
		return this.companyinfoSet;
	}

	/**
	 * Set the set of the å…¬å?¸å®¢æˆ·ä¿¡æ?¯è¡¨.
	 * 
	 * @param customercompanyinfoSet
	 *            The set of å…¬å?¸å®¢æˆ·ä¿¡æ?¯è¡¨
	 */
	public void setCustomercompanyinfoSet(Set<Customercompanyinfo> customercompanyinfoSet) {
		this.customercompanyinfoSet = customercompanyinfoSet;
	}

	/**
	 * Add the å…¬å?¸å®¢æˆ·ä¿¡æ?¯è¡¨.
	 * 
	 * @param customercompanyinfo
	 *            å…¬å?¸å®¢æˆ·ä¿¡æ?¯è¡¨
	 */
	public void addCustomercompanyinfo(Customercompanyinfo customercompanyinfo) {
		this.customercompanyinfoSet.add(customercompanyinfo);
	}

	/**
	 * Get the set of the å…¬å?¸å®¢æˆ·ä¿¡æ?¯è¡¨.
	 * 
	 * @return The set of å…¬å?¸å®¢æˆ·ä¿¡æ?¯è¡¨
	 */
	public Set<Customercompanyinfo> getCustomercompanyinfoSet() {
		return this.customercompanyinfoSet;
	}

	/**
	 * Set the set of the é¡¹ç›®è¡¨.
	 * 
	 * @param projectSet
	 *            The set of é¡¹ç›®è¡¨
	 */
	public void setProjectSet(Set<Project> projectSet) {
		this.projectSet = projectSet;
	}

	/**
	 * Add the é¡¹ç›®è¡¨.
	 * 
	 * @param project
	 *            é¡¹ç›®è¡¨
	 */
	public void addProject(Project project) {
		this.projectSet.add(project);
	}

	/**
	 * Get the set of the é¡¹ç›®è¡¨.
	 * 
	 * @return The set of é¡¹ç›®è¡¨
	 */
	public Set<Project> getProjectSet() {
		return this.projectSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((cid == null) ? 0 : cid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Company other = (Company) obj;
		if (cid == null) {
			if (other.cid != null) {
				return false;
			}
		} else if (!cid.equals(other.cid)) {
			return false;
		}
		return true;
	}

}
