package com.lxzl.db.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of è?Œå·¥çŠ¶æ€?ä¿¡æ?¯è¡¨.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Employeestatusinfo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private Long esiid;

	/** è?Œå·¥çŠ¶æ€?è¡¨. */
	private Employeestatus employeestatus;

	/** è?Œå·¥ä¿¡æ?¯è¡¨. */
	private Employee employee;

	/** åˆ›å»ºæ—¥æœŸ. */
	private Date createTime;

	/** æ›´æ–°æ—¥æœŸ. */
	private Date updateTime;

	/**
	 * Constructor.
	 */
	public Employeestatusinfo() {
	}

	/**
	 * Set the ID.
	 * 
	 * @param esiid
	 *            ID
	 */
	public void setEsiid(Long esiid) {
		this.esiid = esiid;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public Long getEsiid() {
		return this.esiid;
	}

	/**
	 * Set the è?Œå·¥çŠ¶æ€?è¡¨.
	 * 
	 * @param employeestatus
	 *            è?Œå·¥çŠ¶æ€?è¡¨
	 */
	public void setEmployeestatus(Employeestatus employeestatus) {
		this.employeestatus = employeestatus;
	}

	/**
	 * Get the è?Œå·¥çŠ¶æ€?è¡¨.
	 * 
	 * @return è?Œå·¥çŠ¶æ€?è¡¨
	 */
	public Employeestatus getEmployeestatus() {
		return this.employeestatus;
	}

	/**
	 * Set the è?Œå·¥ä¿¡æ?¯è¡¨.
	 * 
	 * @param employee
	 *            è?Œå·¥ä¿¡æ?¯è¡¨
	 */
	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	/**
	 * Get the è?Œå·¥ä¿¡æ?¯è¡¨.
	 * 
	 * @return è?Œå·¥ä¿¡æ?¯è¡¨
	 */
	public Employee getEmployee() {
		return this.employee;
	}

	/**
	 * Set the åˆ›å»ºæ—¥æœŸ.
	 * 
	 * @param createTime
	 *            åˆ›å»ºæ—¥æœŸ
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the åˆ›å»ºæ—¥æœŸ.
	 * 
	 * @return åˆ›å»ºæ—¥æœŸ
	 */
	public Date getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the æ›´æ–°æ—¥æœŸ.
	 * 
	 * @param updateTime
	 *            æ›´æ–°æ—¥æœŸ
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * Get the æ›´æ–°æ—¥æœŸ.
	 * 
	 * @return æ›´æ–°æ—¥æœŸ
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((esiid == null) ? 0 : esiid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Employeestatusinfo other = (Employeestatusinfo) obj;
		if (esiid == null) {
			if (other.esiid != null) {
				return false;
			}
		} else if (!esiid.equals(other.esiid)) {
			return false;
		}
		return true;
	}

}
