package com.lxzl.db.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of EmployeeInfo.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Employeeinfo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private Long eiid;

	/** �?�工信�?�表. */
	private Employee employee;

	/** alias_name. */
	private String aliasName;

	/** 密�?. */
	private String password;

	/** 手机�?�. */
	private String phone;

	/** 邮箱. */
	private String email;

	/** 创建日期. */
	private Date createTime;

	/** 更新日期. */
	private Date updateTime;

	/**
	 * Constructor.
	 */
	public Employeeinfo() {
	}

	/**
	 * Set the ID.
	 * 
	 * @param eiid
	 *            ID
	 */
	public void setEiid(Long eiid) {
		this.eiid = eiid;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public Long getEiid() {
		return this.eiid;
	}

	/**
	 * Set the �?�工信�?�表.
	 * 
	 * @param employee
	 *            �?�工信�?�表
	 */
	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	/**
	 * Get the �?�工信�?�表.
	 * 
	 * @return �?�工信�?�表
	 */
	public Employee getEmployee() {
		return this.employee;
	}

	/**
	 * Set the alias_name.
	 * 
	 * @param aliasName
	 *            alias_name
	 */
	public void setAliasName(String aliasName) {
		this.aliasName = aliasName;
	}

	/**
	 * Get the alias_name.
	 * 
	 * @return alias_name
	 */
	public String getAliasName() {
		return this.aliasName;
	}

	/**
	 * Set the 密�?.
	 * 
	 * @param password
	 *            密�?
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * Get the 密�?.
	 * 
	 * @return 密�?
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * Set the 手机�?�.
	 * 
	 * @param phone
	 *            手机�?�
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * Get the 手机�?�.
	 * 
	 * @return 手机�?�
	 */
	public String getPhone() {
		return this.phone;
	}

	/**
	 * Set the 邮箱.
	 * 
	 * @param email
	 *            邮箱
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * Get the 邮箱.
	 * 
	 * @return 邮箱
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * Set the 创建日期.
	 * 
	 * @param createTime
	 *            创建日期
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 创建日期.
	 * 
	 * @return 创建日期
	 */
	public Date getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the 更新日期.
	 * 
	 * @param updateTime
	 *            更新日期
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * Get the 更新日期.
	 * 
	 * @return 更新日期
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((eiid == null) ? 0 : eiid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Employeeinfo other = (Employeeinfo) obj;
		if (eiid == null) {
			if (other.eiid != null) {
				return false;
			}
		} else if (!eiid.equals(other.eiid)) {
			return false;
		}
		return true;
	}

}
