package com.lxzl.db.bean;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of 类别详细信息.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Categoryinfo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID. */
	private Long ctiid;

	/** 种类. */
	private Category category;

	/** 级别. */
	private Integer level;

	/** 父类别ID. */
	private Long superid;

	/** 创建日期. */
	private Date createTime;

	/** 更新日期. */
	private Date updateTime;

	/**
	 * Constructor.
	 */
	public Categoryinfo() {
	}

	/**
	 * Set the ID.
	 * 
	 * @param ctiid
	 *            ID
	 */
	public void setCtiid(Long ctiid) {
		this.ctiid = ctiid;
	}

	/**
	 * Get the ID.
	 * 
	 * @return ID
	 */
	public Long getCtiid() {
		return this.ctiid;
	}

	/**
	 * Set the 种类.
	 * 
	 * @param category
	 *            种类
	 */
	public void setCategory(Category category) {
		this.category = category;
	}

	/**
	 * Get the 种类.
	 * 
	 * @return 种类
	 */
	public Category getCategory() {
		return this.category;
	}

	/**
	 * Set the 级别.
	 * 
	 * @param level
	 *            级别
	 */
	public void setLevel(Integer level) {
		this.level = level;
	}

	/**
	 * Get the 级别.
	 * 
	 * @return 级别
	 */
	public Integer getLevel() {
		return this.level;
	}

	/**
	 * Set the 父类别ID.
	 * 
	 * @param superid
	 *            父类别ID
	 */
	public void setSuperid(Long superid) {
		this.superid = superid;
	}

	/**
	 * Get the 父类别ID.
	 * 
	 * @return 父类别ID
	 */
	public Long getSuperid() {
		return this.superid;
	}

	/**
	 * Set the 创建日期.
	 * 
	 * @param createTime
	 *            创建日期
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * Get the 创建日期.
	 * 
	 * @return 创建日期
	 */
	public Date getCreateTime() {
		return this.createTime;
	}

	/**
	 * Set the 更新日期.
	 * 
	 * @param updateTime
	 *            更新日期
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * Get the 更新日期.
	 * 
	 * @return 更新日期
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((ctiid == null) ? 0 : ctiid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Categoryinfo other = (Categoryinfo) obj;
		if (ctiid == null) {
			if (other.ctiid != null) {
				return false;
			}
		} else if (!ctiid.equals(other.ctiid)) {
			return false;
		}
		return true;
	}

}
